[project]
name = "ai-platform"
version = "0.1.0"
description = "Production-grade AI backend platform"
authors = [
    {name = "salmanfarooq1",email = "salmanfarooq673@gmail.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
